### ISSUE TITLE
Кафедра юриспруденции

### ISSUE THREAD

**Issue by dimorinny** [rgnlax/Vestnik#1]
Здравствуйте, @rgnlax. Не смог найти кафедру юриспруденции.

Ожидаемое поведение - в выпадающем списке есть пункт: "ЮР".
Текущее поведение - в выпадающем списке нет пункта: "ЮР".
Скриншот -
![Пруф](https://i.imgur.com/IFy4B0K.png)

Окружение - OS X El Capitan 10.11.5 (15F34), Google Chrome Версия 51.0.2704.84 (64-bit).

Спасибо.

**Comment by rgnlax** [comment]
Здравствуйте, @dimorinny. 

Выполнил добавление кафедры ЮР.

Спасибо за замечание.
